/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Anderson Ferreira (https://sketchfab.com/AndersonFS)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cassette-tape-fita-cassete-48ba5a6d926b490c99ff5cd6b6a02530
title: Cassette tape (Fita cassete)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/cassettes.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[97.78, 203.67, 76.29]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.Fita_Low_Fita_Low_0.geometry} material={nodes.Fita_Low_Fita_Low_0.material} />
          </group>
          <group position={[97.78, 223.91, 76.29]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Rodinhas_Low_Rodinhas_Low_0.geometry}
              material={nodes.Rodinhas_Low_Rodinhas_Low_0.material}
            />
          </group>
          <group position={[97.78, 203.67, 76.29]} scale={100}>
            <mesh geometry={nodes.Filme_Low_Filme_Low_0.geometry} material={nodes.Filme_Low_Filme_Low_0.material} />
          </group>
          <group position={[97.78, 23.59, 76.29]} rotation={[-Math.PI / 2, 0, 0]} scale={[15.69, 15.69, 15.69]}>
            <mesh geometry={nodes.Leitor_Low_Leitor_Low_0.geometry} material={nodes.Leitor_Low_Leitor_Low_0.material} />
          </group>
          <group position={[97.86, 56.46, 113.35]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Parafusos_Low_Parafusos_Low_0.geometry}
              material={nodes.Parafusos_Low_Parafusos_Low_0.material}
            />
          </group>
          <group position={[446.17, 20.17, 541.99]} rotation={[3.1, 0.93, -3.11]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.Fita_Low001_Fita_Low_0.geometry} material={nodes.Fita_Low001_Fita_Low_0.material} />
          </group>
          <group position={[462.42, 19.66, 529.94]} rotation={[3.1, 0.93, -3.11]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Rodinhas_Low001_Rodinhas_Low_0.geometry}
              material={nodes.Rodinhas_Low001_Rodinhas_Low_0.material}
            />
          </group>
          <group position={[446.17, 20.17, 541.99]} rotation={[1.56, -0.02, -2.21]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Filme_Low001_Filme_Low_0.geometry}
              material={nodes.Filme_Low001_Filme_Low_0.material}
            />
          </group>
          <group position={[301.59, 24.65, 649.25]} rotation={[3.1, 0.93, -3.11]} scale={[15.69, 15.69, 15.69]}>
            <mesh
              geometry={nodes.Leitor_Low001_Leitor_Low_0.geometry}
              material={nodes.Leitor_Low001_Leitor_Low_0.material}
            />
          </group>
          <group position={[327.13, -13.22, 630.08]} rotation={[3.1, 0.93, -3.11]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Parafusos_Low001_Parafusos_Low_0.geometry}
              material={nodes.Parafusos_Low001_Parafusos_Low_0.material}
            />
          </group>
          <group position={[773.94, 70.01, 419.73]} rotation={[0.37, 1.29, 2.71]} scale={[100, 100, 100]}>
            <mesh geometry={nodes.Fita_Low002_Fita_Low_0.geometry} material={nodes.Fita_Low002_Fita_Low_0.material} />
          </group>
          <group position={[793.41, 68, 424.88]} rotation={[0.37, 1.29, 2.71]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Rodinhas_Low002_Rodinhas_Low_0.geometry}
              material={nodes.Rodinhas_Low002_Rodinhas_Low_0.material}
            />
          </group>
          <group position={[769.88, 72.12, 418.52]} rotation={[1.52, -0.12, -1.32]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Filme_Low002_Filme_Low_0.geometry}
              material={nodes.Filme_Low002_Filme_Low_0.material}
            />
          </group>
          <group position={[600.71, 87.87, 373.89]} rotation={[0.37, 1.29, 2.71]} scale={[15.69, 15.69, 15.69]}>
            <mesh
              geometry={nodes.Leitor_Low002_Leitor_Low_0.geometry}
              material={nodes.Leitor_Low002_Leitor_Low_0.material}
            />
          </group>
          <group position={[636.56, 121.39, 380.6]} rotation={[0.37, 1.29, 2.71]} scale={[100, 100, 100]}>
            <mesh
              geometry={nodes.Parafusos_Low002_Parafusos_Low_0.geometry}
              material={nodes.Parafusos_Low002_Parafusos_Low_0.material}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/cassettes.gltf')
