/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Javier_Fernandez (https://sketchfab.com/Javier.Fernandez)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/jukebox-9fa91a4071664803a39043aeb13ca802
title: Jukebox
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/jukebox1.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-1.14, -1.57, -92]}>
              <mesh geometry={nodes['GramolaLow002_Material_#2_0'].geometry} material={materials.Material_2} />
              <mesh geometry={nodes['GramolaLow002_Material_#1_0'].geometry} material={materials.Material_1} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/jukebox1.gltf')
