/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Mora (https://sketchfab.com/Fopen)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/classic-motorcycle-4b76c94d593b4dc297d91c5c545193da
title: Classic Motorcycle
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/motorcycle.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-84.86, 0, 40.71]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.G_Llanta_MTA_Llanta_0.geometry} material={materials.MTA_Llanta} />
            </group>
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[76.44, -12.15, 101.84]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.G_Asiento_MTA_Asiento_0.geometry} material={materials.MTA_Asiento} />
            </group>
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-42.36, 0, 113.02]} rotation={[1.57, 0, 0.04]}>
              <mesh geometry={nodes.G_Metales_MTA_Metales_0.geometry} material={materials.MTA_Metales} />
            </group>
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-6.7, -13.9, 69.83]} rotation={[Math.PI / 2, 0, 0.26]} scale={[1.01, 1.01, 1.01]}>
              <mesh geometry={nodes.G_Motor_MTA_Motor_0.geometry} material={materials.MTA_Motor} />
            </group>
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.G_Metales_2_MTA_Metales_2_0.geometry} material={materials.MTA_Metales_2} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-16.22, 0.06, 127.04]}>
              <mesh
                geometry={nodes.G_Pintura_Metalica_MTA_Pintura_Metalica_0.geometry}
                material={materials.MTA_Pintura_Metalica}
              />
            </group>
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[95.69, -10.31, 55.63]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.G_Cadena_MTA_Cadena_0.geometry} material={materials.MTA_Cadena} />
            </group>
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-64.64, -23.99, 109.39]} rotation={[Math.PI / 2, -Math.PI / 2, 0]}>
              <mesh geometry={nodes.G_Luces_MTA_Luces_0.geometry} material={materials.MTA_Luces} />
            </group>
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-65.4, -3.93, 39.87]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.G_Cables_MTA_Cables_0.geometry} material={materials.MTA_Cables} />
            </group>
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-65.4, -3.93, 39.87]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.G_freno_MTA_Freno_0.geometry} material={materials.MTA_Freno} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/motorcycle.gltf')
