/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Leam (https://sketchfab.com/leamlld)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/rocks-vinyl-0acd95af0a564f92a1341beeedc51efd
title: rock's vinyl
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/rocks_vinyl.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-1.53, 0.03, 0]} rotation={[3.14, 0.1, -3.14]} scale={[1, 0.02, 1]}>
            <mesh geometry={nodes.Object_4.geometry} material={materials.Vinyl_Face_The_doors} />
            <mesh geometry={nodes.Object_5.geometry} material={materials.tranche} />
          </group>
          <group position={[-1.72, 0.07, 1.66]} rotation={[-3.1, -0.41, 3.13]} scale={[1, 0.02, 1]}>
            <mesh geometry={nodes.Object_7.geometry} material={materials.Vinyl_Face_bowie} />
            <mesh geometry={nodes.Object_8.geometry} material={materials['tranche.001']} />
          </group>
          <group position={[0, -0.02, 0]} scale={6.9}>
            <mesh geometry={nodes.Object_10.geometry} material={materials.Wood} />
          </group>
          <group position={[0.11, 0, -0.1]} rotation={[-Math.PI, 0, -Math.PI]} scale={[1, 0.02, 1]}>
            <mesh geometry={nodes.Object_12.geometry} material={materials.Vinyl_Face_lou_reed} />
            <mesh geometry={nodes.Object_13.geometry} material={materials.tranche} />
          </group>
          <group position={[0.38, 0.03, 1.55]} rotation={[-3.11, -0.18, -3.14]} scale={[1, 0.02, 1]}>
            <mesh geometry={nodes.Object_15.geometry} material={materials.Vinyl_Face_rolling_stone} />
            <mesh geometry={nodes.Object_16.geometry} material={materials['tranche.002']} />
          </group>
          <group position={[1.5, 0.06, 0.49]} rotation={[3.1, 0.39, -3.12]} scale={[1, 0.02, 1]}>
            <mesh geometry={nodes.Object_18.geometry} material={materials.Vinyl_Facethe_who} />
            <mesh geometry={nodes.Object_19.geometry} material={materials['tranche.003']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/rocks_vinyl.gltf')
