/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: mfb64 (https://sketchfab.com/mfb64)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/the-rolling-stones-vinyls-838da4139e3b4d2d8cda5712ae1aa5a5
title: The Rolling Stones Vinyls
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/rolling_stones_vinyl.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.37, 0, 0.18]} rotation={[0, -1.47, 0]}>
            <mesh geometry={nodes.Object_6.geometry} material={materials.label_front4} />
            <mesh geometry={nodes.Object_7.geometry} material={materials.label_back4} />
            <mesh geometry={nodes.Object_8.geometry} material={materials.label_side} />
            <mesh geometry={nodes.Object_4.geometry} material={materials.vinyl} />
          </group>
          <group position={[-0.6, 0, 0.18]}>
            <mesh geometry={nodes.Object_10.geometry} material={materials.cover4_front} />
            <mesh geometry={nodes.Object_11.geometry} material={materials.cover4_back} />
            <mesh geometry={nodes.Object_12.geometry} material={materials.cover4_side} />
            <mesh geometry={nodes.Object_13.geometry} material={materials.cardboard} />
          </group>
          <group position={[-0.51, 0, 0.18]}>
            <mesh geometry={nodes.Object_15.geometry} material={materials['covervinyl4-front']} />
            <mesh geometry={nodes.Object_16.geometry} material={materials['covervinyl4-back']} />
          </group>
          <group position={[-0.32, 0, 0.71]} rotation={[0.02, 0, Math.PI]}>
            <mesh geometry={nodes.Object_20.geometry} material={materials.label_front2} />
            <mesh geometry={nodes.Object_21.geometry} material={materials.label_back2} />
            <mesh geometry={nodes.Object_22.geometry} material={materials.label_side2} />
            <mesh geometry={nodes.Object_18.geometry} material={materials.vinyl} />
          </group>
          <group position={[0, 0, 0.5]}>
            <mesh geometry={nodes.Object_24.geometry} material={materials['cover2-inside']} />
            <mesh geometry={nodes.Object_25.geometry} material={materials['cover2-front']} />
            <mesh geometry={nodes.Object_26.geometry} material={materials['cover2-back']} />
            <mesh geometry={nodes.Object_27.geometry} material={materials.cover2_side} />
            <mesh geometry={nodes.Object_28.geometry} material={materials.cardboard} />
          </group>
          <group position={[0.38, 0, 0.82]} rotation={[0, Math.PI / 9, 0]}>
            <mesh geometry={nodes.Object_32.geometry} material={materials.label_front3} />
            <mesh geometry={nodes.Object_33.geometry} material={materials.label_back3} />
            <mesh geometry={nodes.Object_34.geometry} material={materials.label_side2} />
            <mesh geometry={nodes.Object_30.geometry} material={materials.vinyl} />
          </group>
          <group position={[-0.19, 0, 0.71]} rotation={[0.02, 0, Math.PI]}>
            <mesh geometry={nodes.Object_36.geometry} material={materials['covervinyl1-front']} />
            <mesh geometry={nodes.Object_37.geometry} material={materials['covervinyl1-back']} />
          </group>
          <group position={[0.22, 0, 0.88]} rotation={[0, Math.PI / 9, 0]}>
            <mesh geometry={nodes.Object_39.geometry} material={materials['covervinyl2-front']} />
            <mesh geometry={nodes.Object_40.geometry} material={materials['covervinyl2-back']} />
          </group>
          <group position={[0.79, 0, 0.49]} rotation={[0, -0.26, 0]}>
            <mesh geometry={nodes.Object_42.geometry} material={materials.Exile_poster} />
            <mesh geometry={nodes.Object_43.geometry} material={materials.Exile_poster_back} />
          </group>
          <group position={[-0.67, 0, 0.28]} rotation={[0, 0.44, 0]}>
            <mesh geometry={nodes.Object_45.geometry} material={materials.cover5_front} />
            <mesh geometry={nodes.Object_46.geometry} material={materials.cover5_back} />
            <mesh geometry={nodes.Object_47.geometry} material={materials.cover5_side} />
            <mesh geometry={nodes.Object_48.geometry} material={materials.cardboard} />
          </group>
          <group position={[-0.66, 0, 0.28]} rotation={[0, -1.03, 0]}>
            <mesh geometry={nodes.Object_52.geometry} material={materials.label_front5} />
            <mesh geometry={nodes.Object_53.geometry} material={materials.label_back5} />
            <mesh geometry={nodes.Object_54.geometry} material={materials.label_side} />
            <mesh geometry={nodes.Object_50.geometry} material={materials.vinyl} />
          </group>
          <group position={[0, 0, -0.02]} rotation={[0, -0.26, 0]}>
            <mesh geometry={nodes.Object_56.geometry} material={materials.cover1_front} />
            <mesh geometry={nodes.Object_57.geometry} material={materials.cover1_back} />
            <mesh geometry={nodes.Object_58.geometry} material={materials.cover1_side} />
            <mesh geometry={nodes.Object_59.geometry} material={materials.cardboard} />
          </group>
          <group position={[0.14, 0, 0.02]} rotation={[0, -1.47, 0]}>
            <mesh geometry={nodes.Object_63.geometry} material={materials.label_front} />
            <mesh geometry={nodes.Object_64.geometry} material={materials.label_back} />
            <mesh geometry={nodes.Object_65.geometry} material={materials.label_side} />
            <mesh geometry={nodes.Object_61.geometry} material={materials.vinyl} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/rolling_stones_vinyl.gltf')
