/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Emanuel Silva (https://sketchfab.com/Emanuel.Silva)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/vinyl-disk-and-cover-5bb73fe742c34e6484923c2462f5554a
title: Vinyl Disk and Cover
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/vinyl_disk_cover.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Vinyl_disk001_Vinyl_inner_0.geometry} material={materials.Vinyl_inner} />
            <mesh geometry={nodes.Vinyl_disk001_Vinyl_inner_0_1.geometry} material={materials.Vinyl_inner} />
            <mesh geometry={nodes.Vinyl_disk001_Label_0.geometry} material={materials.Label} />
            <mesh geometry={nodes.Vinyl_disk001_Vinyl_outer_0.geometry} material={materials.Vinyl_outer} />
          </group>
          <group position={[-14.52, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={17.9}>
            <group scale={5.59}>
              <mesh geometry={nodes.Vinyl_Cover_Cover_0.geometry} material={materials.Cover} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/vinyl_disk_cover.gltf')
